BEGIN;
CREATE TABLE IF NOT EXISTS users (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(150) NOT NULL,
 email varchar(254) NOT NULL UNIQUE CHECK (email = lower(email)),
 phone varchar(40) NOT NULL DEFAULT '',
 password_hash text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS animals (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(150) NOT NULL, species varchar(80) NOT NULL,
 age_text varchar(80) NOT NULL DEFAULT '', gender varchar(40) NOT NULL DEFAULT '',
 size varchar(40) NOT NULL DEFAULT '', status varchar(80) NOT NULL DEFAULT 'Disponível',
 description text NOT NULL DEFAULT '', image_path text,
 featured smallint NOT NULL DEFAULT 0 CHECK (featured IN (0,1))
);
CREATE TABLE IF NOT EXISTS campaigns (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title varchar(200) NOT NULL, description text NOT NULL DEFAULT '',
 goal_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (goal_amount >= 0),
 raised_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (raised_amount >= 0),
 pix_key text, image_path text,
 featured smallint NOT NULL DEFAULT 0 CHECK (featured IN (0,1)),
 active smallint NOT NULL DEFAULT 1 CHECK (active IN (0,1))
);
CREATE TABLE IF NOT EXISTS news (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title varchar(200) NOT NULL, summary text NOT NULL DEFAULT '',
 content text, image_path text, published_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS settings (
 id integer PRIMARY KEY CHECK (id = 1), org_name varchar(150) NOT NULL,
 tagline text, about_text text, mission_text text, whatsapp text, pix_key text,
 instagram text, address text, donation_notice text
);
INSERT INTO settings (id, org_name) VALUES (1, 'Amigos de Patas') ON CONFLICT (id) DO NOTHING;
CREATE TABLE IF NOT EXISTS adoption_requests (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 animal_id integer NOT NULL REFERENCES animals(id),
 full_name varchar(150) NOT NULL, email varchar(254) NOT NULL,
 phone varchar(40) NOT NULL, city varchar(150) NOT NULL,
 message text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS adoption_requests_animal_idx ON adoption_requests(animal_id);
COMMIT;
