-- PostgreSQL 16+. Execute em um banco vazio. Não apaga tabelas existentes.
BEGIN;
SET LOCAL TIME ZONE 'America/Sao_Paulo';
CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  telefone VARCHAR(30) NULL,
  senha_hash VARCHAR(255) NOT NULL,
  tipo VARCHAR(30) CHECK (tipo IN ('usuario','administrador')) NOT NULL DEFAULT 'usuario',
  status VARCHAR(30) CHECK (status IN ('ativo','inativo')) NOT NULL DEFAULT 'ativo',
  aceitou_privacidade SMALLINT CHECK (aceitou_privacidade IN (0, 1)) NOT NULL DEFAULT 0,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expira_em TIMESTAMP NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultimo_uso_em TIMESTAMP NULL,
  CONSTRAINT fk_sessoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE animais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  especie VARCHAR(30) CHECK (especie IN ('cao','gato','outro')) NOT NULL,
  raca VARCHAR(100) NULL,
  sexo VARCHAR(30) CHECK (sexo IN ('macho','femea','nao_informado')) NOT NULL DEFAULT 'nao_informado',
  idade_aproximada VARCHAR(80) NULL,
  porte VARCHAR(30) CHECK (porte IN ('pequeno','medio','grande','nao_informado')) NOT NULL DEFAULT 'nao_informado',
  descricao TEXT NULL,
  comportamento TEXT NULL,
  estado_saude TEXT NULL,
  vacinado SMALLINT CHECK (vacinado IN (0, 1)) NOT NULL DEFAULT 0,
  castrado SMALLINT CHECK (castrado IN (0, 1)) NOT NULL DEFAULT 0,
  status VARCHAR(30) CHECK (status IN ('disponivel','em_analise','reservado','adotado','indisponivel')) NOT NULL DEFAULT 'disponivel',
  foto_principal VARCHAR(500) NULL,
  data_resgate DATE NULL,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fotos_animais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id BIGINT NOT NULL,
  arquivo VARCHAR(500) NOT NULL,
  descricao VARCHAR(255) NULL,
  ordem INT NOT NULL DEFAULT 0,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fotos_animal FOREIGN KEY (animal_id) REFERENCES animais(id) ON DELETE CASCADE
);

CREATE TABLE solicitacoes_adocao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  animal_id BIGINT NOT NULL,
  tipo_moradia VARCHAR(80) NOT NULL,
  possui_quintal SMALLINT CHECK (possui_quintal IN (0, 1)) NOT NULL DEFAULT 0,
  possui_outros_animais SMALLINT CHECK (possui_outros_animais IN (0, 1)) NOT NULL DEFAULT 0,
  quantidade_pessoas INT NOT NULL DEFAULT 1,
  todos_concordam SMALLINT CHECK (todos_concordam IN (0, 1)) NOT NULL DEFAULT 0,
  motivo_adocao TEXT NOT NULL,
  experiencia_com_animais TEXT NULL,
  observacoes TEXT NULL,
  status VARCHAR(30) CHECK (status IN ('pendente','em_analise','entrevista','aprovada','recusada','cancelada','concluida')) NOT NULL DEFAULT 'pendente',
  resposta_ong TEXT NULL,
  data_solicitacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_adocoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
  CONSTRAINT fk_adocoes_animal FOREIGN KEY (animal_id) REFERENCES animais(id) ON DELETE RESTRICT
);

CREATE TABLE campanhas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(180) NOT NULL,
  descricao TEXT NOT NULL,
  meta DECIMAL(12,2) NOT NULL DEFAULT 0,
  valor_arrecadado DECIMAL(12,2) NOT NULL DEFAULT 0,
  imagem VARCHAR(500) NULL,
  chave_pix VARCHAR(255) NULL,
  tipo_chave_pix VARCHAR(30) CHECK (tipo_chave_pix IN ('cpf','cnpj','email','telefone','aleatoria','nao_informado')) NOT NULL DEFAULT 'nao_informado',
  status VARCHAR(30) CHECK (status IN ('rascunho','ativa','encerrada')) NOT NULL DEFAULT 'ativa',
  data_inicio DATE NULL,
  data_fim DATE NULL,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE noticias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  resumo VARCHAR(500) NULL,
  conteudo TEXT NOT NULL,
  imagem VARCHAR(500) NULL,
  status VARCHAR(30) CHECK (status IN ('rascunho','publicada')) NOT NULL DEFAULT 'publicada',
  autor_id BIGINT NULL,
  data_publicacao TIMESTAMP NULL,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_noticias_autor FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  descricao TEXT NULL,
  url VARCHAR(500) NOT NULL,
  status VARCHAR(30) CHECK (status IN ('rascunho','publicado')) NOT NULL DEFAULT 'publicado',
  data_publicacao TIMESTAMP NULL,
  data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE configuracoes (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  nome_ong VARCHAR(160) NOT NULL DEFAULT 'ONG de Proteção Animal',
  descricao TEXT NULL,
  telefone VARCHAR(40) NULL,
  email VARCHAR(160) NULL,
  endereco VARCHAR(255) NULL,
  chave_pix VARCHAR(255) NULL,
  tipo_chave_pix VARCHAR(30) CHECK (tipo_chave_pix IN ('cpf','cnpj','email','telefone','aleatoria','nao_informado')) NOT NULL DEFAULT 'nao_informado',
  instagram VARCHAR(255) NULL,
  facebook VARCHAR(255) NULL,
  youtube VARCHAR(255) NULL,
  politica_privacidade TEXT NULL,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE logs_administrativos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  administrador_id BIGINT NULL,
  acao VARCHAR(120) NOT NULL,
  tabela_afetada VARCHAR(120) NULL,
  registro_id BIGINT NULL,
  detalhes TEXT NULL,
  endereco_ip VARCHAR(45) NULL,
  data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_logs_admin FOREIGN KEY (administrador_id) REFERENCES usuarios(id) ON DELETE SET NULL
);


CREATE INDEX idx_usuarios_tipo_status ON usuarios (tipo, status);
CREATE INDEX idx_sessoes_expira ON sessoes (expira_em);
CREATE INDEX idx_animais_filtros ON animais (especie, sexo, porte, status);
CREATE INDEX idx_fotos_animal_ordem ON fotos_animais (animal_id, ordem);
CREATE INDEX idx_adocoes_status ON solicitacoes_adocao (status);
CREATE INDEX idx_adocoes_usuario ON solicitacoes_adocao (usuario_id);
CREATE INDEX idx_adocoes_animal ON solicitacoes_adocao (animal_id);
CREATE INDEX idx_campanhas_status ON campanhas (status);
CREATE INDEX idx_noticias_status_data ON noticias (status, data_publicacao);
CREATE INDEX idx_videos_status_data ON videos (status, data_publicacao);
CREATE INDEX idx_logs_data ON logs_administrativos (data_registro);

-- Mantém a atualização automática existente no esquema original.
CREATE FUNCTION atualizar_data_modificacao() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.data_atualizacao = clock_timestamp() AT TIME ZONE 'America/Sao_Paulo';
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_usuarios_atualizacao BEFORE UPDATE ON usuarios
FOR EACH ROW EXECUTE FUNCTION atualizar_data_modificacao();
CREATE TRIGGER trg_animais_atualizacao BEFORE UPDATE ON animais
FOR EACH ROW EXECUTE FUNCTION atualizar_data_modificacao();
CREATE TRIGGER trg_solicitacoes_adocao_atualizacao BEFORE UPDATE ON solicitacoes_adocao
FOR EACH ROW EXECUTE FUNCTION atualizar_data_modificacao();
CREATE TRIGGER trg_campanhas_atualizacao BEFORE UPDATE ON campanhas
FOR EACH ROW EXECUTE FUNCTION atualizar_data_modificacao();
CREATE TRIGGER trg_noticias_atualizacao BEFORE UPDATE ON noticias
FOR EACH ROW EXECUTE FUNCTION atualizar_data_modificacao();
CREATE TRIGGER trg_videos_atualizacao BEFORE UPDATE ON videos
FOR EACH ROW EXECUTE FUNCTION atualizar_data_modificacao();
CREATE TRIGGER trg_configuracoes_atualizacao BEFORE UPDATE ON configuracoes
FOR EACH ROW EXECUTE FUNCTION atualizar_data_modificacao();

CREATE UNIQUE INDEX idx_usuarios_email_normalizado ON usuarios (lower(email));

COMMIT;
